name: 'C&R Preferred, LLC '
favicon: null
layout_spectrum: 0.65925
typography_spectrum: 0.74433
title: 'C&R Company Page'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bbbbbb'
    - '#8a8068'
    - '#ebecf0'
    - '#232323'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
