name: 'C&R Preferred, LLC '
favicon: null
layout_spectrum: 0.25725
typography_spectrum: 0.74433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccd6df'
    - '#3d5c80'
    - '#fefefe'
    - '#6287aa'
    - '#1e2735'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
