name: 'C&R Preferred, LLC '
favicon: null
layout_spectrum: 0.25063
typography_spectrum: 0.74433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#394b64'
    - '#83b9ed'
    - '#ccd6df'
    - '#6488ab'
    - '#b29b8f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
