name: 'C&R Preferred, LLC '
favicon: null
layout_spectrum: 0.25725
typography_spectrum: 0.74433
title: 'C&R Company Page'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#919191'
    - '#000000'
    - '#555555'
    - '#cacad5'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
