name: 'C&R Preferred, LLC '
favicon: null
layout_spectrum: 0.54786
typography_spectrum: 0.75189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040301'
    - '#ffffff'
    - '#b6b6b6'
    - '#7d7d7d'
    - '#4b3a31'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
